
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.1]
///On Version Program [0111]
///Generated by: Threerapat
///Generated on: 25/06/2025 17:10:53
///***********************************************************************************
import EntityBase from "@/Model/Shared/EntityBase";

class AreaModelGenerated extends EntityBase {
    public AreaCode : string ;
    public AreaName : string ;
    public StartDate : Date ;
    public FinishDate : Date ;
    public AbbreviationName : string ;
    public AreaType : string ;
    public DepartmentId : string ;
    public EmailAddress : string ;
    public PaymentPort : string ;
    public ReleaseIndicator : string ;
    public LoadIndicator : string ;
    public ReleaseIndicatorImport : string ;
    public DischargeIndicator : string ;
    public CreateDate : Date ;
    public CreateUser : string ;
    public UpdateDate : Date ;
    public UpdateUser : string ;

    // Pk Original //
    public OriginalAreaCode : string ;
    // Pk Original //
}
export default AreaModelGenerated;

