
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.0]
///On Version Program [Beta]
///Generated by: Threerapat
///Generated on: 29/05/2025 13:44:08
///***********************************************************************************
import ModelGenerated from "./AreaModel.Generated"



class AreaModel extends ModelGenerated {


}
export default AreaModel;
