
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.1]
///On Version Program [0111]
///Generated by: Threerapat
///Generated on: 27/06/2025 14:56:39
///***********************************************************************************
import EntityBase from "@/Model/Shared/EntityBase";

class BankModelGenerated extends EntityBase {
    public BankCode : string ;
    public BankName : string ;
    public CreateDate : Date ;
    public CreateUser : string ;
    public UpdateDate : Date ;
    public UpdateUser : string ;

    // Pk Original //
    public OriginalBankCode : string ;
    // Pk Original //
}
export default BankModelGenerated;

