
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.1]
///On Version Program [0111]
///Generated by: Threerapat
///Generated on: 27/06/2025 14:51:43
///***********************************************************************************
import ModelGenerated from "./BankModel.Generated"



class BankModel extends ModelGenerated {

}
export default BankModel;
