
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.1]
///On Version Program [0111]
///Generated by: Threerapat
///Generated on: 30/05/2025 16:07:21
///***********************************************************************************
import EntityBase from "@/Model/Shared/EntityBase";

class BrokerModelGenerated extends EntityBase {
    public BrkTaxNo : string ;
    public BrkBrnNo : number ;
    public BrkNameEng : string ;
    public BrkNameThai : string ;
    public StreetAndNo : string ;
    public DistrictName : string ;
    public SubProvinceName : string ;
    public ProvinceName : string ;
    public PostCode : string ;
    public EmailAddress : string ;
    public Telephone : string ;
    public Fax : string ;
    public IsDefaultBroker : boolean ;
    public Note1 : string ;
    public CreateDate : Date ;
    public CreateUser : string ;
    public UpdateDate : Date ;
    public UpdateUser : string ;
    public AeosReferenceNo : string ;

    // Pk Original //
    public OriginalBrkTaxNo : string ;
    public OriginalBrkBrnNo : number ;
    // Pk Original //
}
export default BrokerModelGenerated;

