
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.1]
///On Version Program [0111]
///Generated by: Threerapat
///Generated on: 30/05/2025 16:07:21
///***********************************************************************************
import ModelGenerated from "./BrokerModel.Generated"



class BrokerModel extends ModelGenerated {

}
export default BrokerModel;
