
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.1]
///On Version Program [0111]
///Generated by: Threerapat
///Generated on: 26/06/2025 17:02:29
///***********************************************************************************
import ModelGenerated from "./VAreaModel.Generated"



class VAreaModel extends ModelGenerated {

}
export default VAreaModel;
