
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.0]
///On Version Program [Beta]
///Generated by: Threerapat
///Generated on: 29/05/2025 13:32:34
///***********************************************************************************
import ModelGenerated from "./VAreaModel.Generated"



class VAreaModel extends ModelGenerated {

}
export default VAreaModel;
