
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.0]
///On Version Program [1.0.0]
///Generated by: Threerapat
///Generated on: 12/03/2025 14:56:37
///***********************************************************************************
//#region Import
import express from "express";
import controller from "../../Controller/Master/ControllerDepot"
import JsonReq from "../../Model/Shared/JsonReq";
import Result from "../../Model/Shared/Result";
import AuthenticateJWT from "../../Common/Auth";
import { Request, Response } from "express";
import ActionCode from "../../Constants/ActionCode";
import ProgramCode from "../../Constants/ProgramCode";
import ConfigSys from "../../Config/ConfigSys";

//#endregion Import

//#region Fields
const router = express.Router();
const blDepot = new controller();
const auth = new AuthenticateJWT();
const programCode: string = new ProgramCode().Depot
const actionCode = new ActionCode();

//#endregion Fields

//#region Document
router.get("/Document", (req: Request, res: Response) => {
  const key = req.query.key;
  if (key === ConfigSys.DocumentKey) {
    res.send(blDepot.Document());
  }
  else {
    res.send("Not Access");
  }

});
//#endregion Document

//#region GetAll
router.post("/GetAll", auth.authenticateJWT(programCode, actionCode.Access), async (req: Request, res: Response): Promise<void> => {
  let result: Result
  try {
    let json: JsonReq = req.body;
    result = await blDepot.GetAll(json)
    res.status(200).json(result)
  } catch (error) {
    res.status(400).json(result)
  }
});


//#endregion GetAll

// //#region Find
router.post("/Find", auth.authenticateJWT(programCode, actionCode.Access), async (req: Request, res: Response): Promise<void> => {
  let result: Result
  try {
    let json: JsonReq = req.body;
    result = await blDepot.Find(json)
    res.status(200).json(result)
  } catch (error) {
    res.status(400).json(result)
  }
});
// //#endregion Find

// //#region GetCount
router.post("/GetCount", auth.authenticateJWT(programCode, actionCode.Access), async (req: Request, res: Response): Promise<void> => {
  let result: Result
  try {
    let json: JsonReq = req.body;
    result = await blDepot.GetCount(json)
    res.status(200).json(result)
  } catch (error) {
    res.status(400).json(result)
  }
});
// //#endregion GetCount

// //#region GetPaged
router.post("/GetPaged", auth.authenticateJWT(programCode, actionCode.Access), async (req: Request, res: Response): Promise<void> => {
  let result: Result
  try {
    let json: JsonReq = req.body;
    result = await blDepot.GetPaged(json)
    res.status(200).json(result)
  } catch (error) {
    res.status(400).json(result)
  }
});
// //#endregion GetPaged

// //#region GetByAny
router.post("/GetByAny", auth.authenticateJWT(programCode, actionCode.Access), async (req: Request, res: Response): Promise<void> => {
  let result: Result
  try {
    let json: JsonReq = req.body;
    result = await blDepot.GetByAny(json)
    res.status(200).json(result)
  } catch (error) {
    res.status(400).json(result)
  }
});
// //#endregion GetByAny

// //#region DeleteWhere
router.delete("/DeleteWhere", auth.authenticateJWT(programCode, actionCode.Delete), async (req: Request, res: Response): Promise<void> => {
  let result: Result
  try {
    let json: JsonReq = req.body;
    result = await blDepot.DeleteWhere(json)
    res.status(200).json(result)
  } catch (error) {
    res.status(400).json(result)
  }
});
// //#endregion DeleteWhere

// //#region Delete
router.delete("/Delete", auth.authenticateJWT(programCode, actionCode.Delete), async (req: Request, res: Response): Promise<void> => {
  let result: Result
  try {
    let json: JsonReq = req.body;
    result = await blDepot.Delete(json)
    res.status(200).json(result)
  } catch (error) {
    res.status(400).json(result)
  }
});
// //#endregion Delete

// //#region GetRecord
router.post("/GetRecord", auth.authenticateJWT(programCode, actionCode.Access), async (req: Request, res: Response): Promise<void> => {
  let result: Result
  try {
    let json: JsonReq = req.body;
    result = await blDepot.GetRecord(json)
    res.status(200).json(result)
  } catch (error) {
    res.status(400).json(result)
  }
});
// //#endregion GetRecord

// //#region Insert
router.post("/Insert", auth.authenticateJWT(programCode, actionCode.Insert), async (req: Request, res: Response): Promise<void> => {
  let result: Result
  try {
    let json: JsonReq = req.body;
    result = await blDepot.Insert(json)
    res.status(200).json(result)
  } catch (error) {
    res.status(400).json(result)
  }
});
// //#endregion Insert

// //#region Update
router.put("/Update", auth.authenticateJWT(programCode, actionCode.Update), async (req: Request, res: Response): Promise<void> => {
  let result: Result
  try {
    let json: JsonReq = req.body;
    result = await blDepot.Update(json)
    res.status(200).json(result)
  } catch (error) {
    res.status(400).json(result)
  }
});
// //#endregion Update


//#region Export Default
export default router;
//#endregion Export Default
