
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.1]
///On Version Program [0111]
///Generated by: Threerapat
///Generated on: 23/06/2025 09:27:57
///***********************************************************************************

import ControllerBase from "@/Controller/ControllerBaseTable"
import sql from "mssql";
import Model from "@/Model/Master/AreaModel"
import Schema from "@/Model/Shared/Schema";
import SchemaData from "@/Schema/Master/Area.json"

class ControllerAreaGenerated extends ControllerBase {

    constructor() {
        super();
        this.tableNameFull = "T_M_AREA";
        this.tableName = "AREA";
        this.tableNameNormal = "Area";
        this.generateDate = "23/06/2025 09:27:57";
        this.generateBy = "Threerapat"
        this.version = "0111";
    }



    protected async GetRequestSave(json: any, state: string): Promise<any> {
        let entity: Model = json
        let request = await this.CreateRequest(entity.Tran);
        if (state === "edit") {
            request.input("ORIGINAL_AREA_CODE", sql.NChar, entity.AreaCode);

        } else {
        }
        request.input("AREA_CODE", sql.NChar, entity.AreaCode);
        request.input("AREA_NAME", sql.NVarChar, entity.AreaName);
        request.input("START_DATE", sql.DateTime, entity.StartDate);
        request.input("FINISH_DATE", sql.DateTime, entity.FinishDate);
        request.input("ABBREVIATION_NAME", sql.NVarChar, entity.AbbreviationName);
        request.input("AREA_TYPE", sql.NVarChar, entity.AreaType);
        request.input("DEPARTMENT_ID", sql.NVarChar, entity.DepartmentId);
        request.input("EMAIL_ADDRESS", sql.NVarChar, entity.EmailAddress);
        request.input("PAYMENT_PORT", sql.NVarChar, entity.PaymentPort);
        request.input("RELEASE_INDICATOR", sql.NVarChar, entity.ReleaseIndicator);
        request.input("LOAD_INDICATOR", sql.NVarChar, entity.LoadIndicator);
        request.input("RELEASE_INDICATOR_IMPORT", sql.NVarChar, entity.ReleaseIndicatorImport);
        request.input("DISCHARGE_INDICATOR", sql.NVarChar, entity.DischargeIndicator);
        request.input("CREATE_DATE", sql.DateTime, entity.CreateDate);
        request.input("CREATE_USER", sql.NVarChar, entity.CreateUser);
        request.input("UPDATE_DATE", sql.DateTime, entity.UpdateDate);
        request.input("UPDATE_USER", sql.NVarChar, entity.UpdateUser);
        return request
    }

    protected async GetRequestByPrimaryKey(json: any): Promise<any> {
        let entity: Model = json
        let request = await this.CreateRequest(entity.Tran);
        request.input("AREA_CODE", sql.NChar, entity.AreaCode);
        return request
    }

    protected async GetEntitySave(json: any, data: any): Promise<{}> {
        let entity: Model = json
        return entity
    }

    protected async GetSchema(): Promise<Schema[]> {
        let data: any[] = SchemaData
        let listSchema: Schema[] = data
        return listSchema;
    }

    protected DocumentBody(): string {
        let documentText: string = super.DocumentBody();
        return documentText
    }

    protected GetColumnDocument(state: string): string {
        let columnDocument: string
        let entity: Model = new Model();
        const currentDate: Date = new Date();
        
        if (state === "edit") {
        entity.OriginalAreaCode = "string";
        }


        // Start All Column
        entity.AreaCode = "string";
        entity.AreaName = "string";
        entity.StartDate = currentDate;
        entity.FinishDate = currentDate;
        entity.AbbreviationName = "string";
        entity.AreaType = "string";
        entity.DepartmentId = "string";
        entity.EmailAddress = "string";
        entity.PaymentPort = "string";
        entity.ReleaseIndicator = "string";
        entity.LoadIndicator = "string";
        entity.ReleaseIndicatorImport = "string";
        entity.DischargeIndicator = "string";
        entity.CreateDate = currentDate;
        entity.CreateUser = "string";
        entity.UpdateDate = currentDate;
        entity.UpdateUser = "string";
        // End All Column
        columnDocument = JSON.stringify(entity)
        return columnDocument;
    }

    protected GetColumnDocumentPrimaryKey(): string {
        let columnDocument: string
        let entity: Model = new Model();
        // Start Primary Key
        entity.AreaCode = "string";
        //End Primary Key
        columnDocument = JSON.stringify(entity)
        return columnDocument
    }


}
export default ControllerAreaGenerated;
