
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.1]
///On Version Program [0111]
///Generated by: Threerapat
///Generated on: 27/06/2025 09:10:54
///***********************************************************************************

import ControllerBase from "./ControllerVArea.Generated"
import ErrorMessage from "@/Model/Shared/ErrorMessage";
import Model from "@/Model/View/Master/VAreaModel"
import Document from "@/Common/Document";

class ControllerVArea extends ControllerBase {
}
export default ControllerVArea;
