
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.1]
///On Version Program [0111]
///Generated by: Threerapat
///Generated on: 27/06/2025 14:40:43
///***********************************************************************************

import ControllerBase from "@/Controller/ControllerBase"
import sql from "mssql";
import Model from "@/Model/View/Master/VAreaModel"
import Schema from "@/Model/Shared/Schema";
import SchemaData from "@/Schema/View/Master/VArea.json"

class ControllerVAreaGenerated extends ControllerBase {

    constructor() {
        super();
        this.tableNameFull = "V_AREA";
        this.tableName = "VAREA";
        this.tableNameNormal = "VArea";
        this.generateDate = "27/06/2025 14:40:43";
        this.generateBy = "Threerapat"
        this.version = "0111";
    }

    protected async GetSchema(): Promise<Schema[]> {
        let data: any[] = SchemaData
        let listSchema: Schema[] = data
        return listSchema;
    }



}
export default ControllerVAreaGenerated;
