
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.0]
///On Version Program [Beta]
///Generated by: Threerapat
///Generated on: 29/05/2025 13:32:31
///***********************************************************************************

import ControllerBase from "./ControllerVArea.Generated"
import ErrorMessage from "@/Model/Shared/ErrorMessage";
import Model from "@/Model/View/Master//VAreaModel"
import Document from "@/Common/Document";

class ControllerVArea extends ControllerBase {
}
export default ControllerVArea;
