
///***********************************************************************************
///Copyright by [CDSCOM]
///On Version Template [1.0.0]
///On Version Program [Beta]
///Generated by: Threerapat
///Generated on: 29/05/2025 13:32:31
///***********************************************************************************

import ControllerBase from "@/Controller/ControllerBase"
import sql from "mssql";
import Model from "@/Model/View/Master//VAreaModel"
class ControllerVAreaGenerated extends ControllerBase {

    constructor() {
        super();
        this.tableNameFull = "V_AREA";
        this.tableName = "VAREA";
        this.tableNameNormal = "VArea";
        this.generateDate = "29/05/2025 13:32:31";
        this.generateBy = "Threerapat"
        this.version = "Beta";
    }



}
export default ControllerVAreaGenerated;
